[versions]
agp = "8.13.1"
aetherTransportFile = "2.0.13"
aznavrail = "main-SNAPSHOT"
coreKtx = "1.17.0"
dependencyresolver = "main-SNAPSHOT"
googleGenai = "1.28.0"
kotlinxCoroutinesCore = "1.10.2"
kxml2 = "2.3.0"
mockwebserver = "5.3.2"
preferenceKtx = "1.2.1"
mavenResolver = "2.0.13"
mavenResolverHttp = "1.9.24"
mavenCore = "3.9.11"
mavenSettingsBuilder = "3.9.11"
wagonHttp = "3.5.3"
jaxbApi = "2.3.1"
javaxAnnotation = "1.3.2"
validationApi = "1.1.0.Final"
javaxEl = "3.0.0"
glassfishEl = "3.0.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinxSerializationJson = "1.9.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
kotlin = "2.2.21"
composeBom = "2025.11.01"
materialIconsExtended = "1.7.8"
localbroadcastmanager = "1.1.0"
navigationCompose = "2.9.6"
okhttp = "5.3.2"
orgEclipseJgit = "6.9.0.202403050737-r"
retrofit = "3.0.0"
retrofit2KotlinxSerializationConverter = "1.0.0"
runtimeLivedata = "1.9.5"
slf4jAndroid = "2.0.17-0"
slf4jApi = "2.0.17"
slf4jSimple = "2.0.17"
composeUnstyledCore = "1.49.2"
generativeai = "0.9.0"
haze = "1.7.0"
kotlincAndroid = "fce2462f00"
nbJavac = "17.0.0.3"
guava = "33.4.8-android"
r8 = "8.9.35"
soraEditor = "0.23.5"
scalaCompiler = "3.6.3"
smali = "2.5.2"

[libraries]
smali = { module = "org.smali:smali", version.ref = "smali" }
baksmali = { module = "org.smali:baksmali", version.ref = "smali" }
sora-editor = { module = "io.github.Rosemoe.sora-editor:editor", version.ref = "soraEditor" }
scala-compiler = { module = "org.scala-lang:scala3-compiler_3", version.ref = "scalaCompiler" }
kotlinc-android = { module = "com.github.Cosmic-Ide.kotlinc-android:kotlinc-android", version.ref = "kotlincAndroid" }
nb-javac-android = { module = "io.github.itsaky:nb-javac-android", version.ref = "nbJavac" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
r8 = { module = "com.android.tools:r8", version.ref = "r8" }
aether-transport-file = { group = "org.apache.maven.resolver", name = "maven-resolver-transport-file", version.ref = "aetherTransportFile" }
dependencyresolverr = { module = "com.github.Cosmic-Ide:DependencyResolver", version.ref = "dependencyresolver" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kxml2 = { module = "net.sf.kxml:kxml2", version.ref = "kxml2" }
maven-resolver-api = { group = "org.apache.maven.resolver", name = "maven-resolver-api", version.ref = "mavenResolver" }
maven-resolver-spi = { group = "org.apache.maven.resolver", name = "maven-resolver-spi", version.ref = "mavenResolver" }
maven-resolver-util = { group = "org.apache.maven.resolver", name = "maven-resolver-util", version.ref = "mavenResolver" }
maven-resolver-impl = { group = "org.apache.maven.resolver", name = "maven-resolver-impl", version.ref = "mavenResolver" }
maven-resolver-connector-basic = { group = "org.apache.maven.resolver", name = "maven-resolver-connector-basic", version.ref = "mavenResolver" }
maven-resolver-transport-http = { group = "org.apache.maven.resolver", name = "maven-resolver-transport-http", version.ref = "mavenResolverHttp" }
maven-resolver-provider = { group = "org.apache.maven", name = "maven-resolver-provider", version.ref = "mavenCore" }
maven-resolver-supplier = { group = "org.apache.maven", name = "maven-resolver-supplier", version.ref = "mavenResolverHttp" }
maven-repository-metadata = { group = "org.apache.maven", name = "maven-repository-metadata", version.ref = "mavenCore" }

androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-localbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "localbroadcastmanager" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
aznavrail = { module = "com.github.HereLiesAz:AzNavRail", version.ref = "aznavrail" }
google-genai = { module = "com.google.genai:google-genai", version.ref = "googleGenai" }
maven-core = { module = "org.apache.maven:maven-core", version.ref = "mavenCore" }
maven-settings-builder = { module = "org.apache.maven:maven-settings-builder", version.ref = "mavenSettingsBuilder" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
resolver-maven-resolver-supplier = { module = "org.apache.maven.resolver:maven-resolver-supplier", version.ref = "mavenResolverHttp" }
wagon-http-lightweight = { module = "org.apache.maven.wagon:wagon-http-lightweight", version.ref = "wagonHttp" }
wagon-provider-api = { module = "org.apache.maven.wagon:wagon-provider-api", version.ref = "wagonHttp" }
wagon-file = { module = "org.apache.maven.wagon:wagon-file", version.ref = "wagonHttp" }
jaxb-api = { module = "javax.xml.bind:jaxb-api", version.ref = "jaxbApi" }
javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version.ref = "javaxAnnotation" }
validation-api = { module = "javax.validation:validation-api", version.ref = "validationApi" }
javax-el = { module = "javax.el:javax.el-api", version.ref = "javaxEl" }
glassfish-el = { module = "org.glassfish:javax.el", version.ref = "glassfishEl" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-platform = { group = "androidx.compose.ui", name = "ui-platform" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" }
compose-unstyled-core = { module = "com.composables:core", version.ref = "composeUnstyledCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
org-eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "orgEclipseJgit" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
slf4j-android = { module = "uk.uuid.slf4j:slf4j-android", version.ref = "slf4jAndroid" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4jSimple" }
generativeai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeai" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
